# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d50f6b2e658602510bba6473944f7a2e29576442fc2ec84bef00b7c57dc6a28884492c125632b694c0c7966df5e6f60a366c2014e21d8aa7b8dd2c454aa2c53

test:
  secret_key_base: 7086822cdf773d4d5c222fcf7ed495714c8147d90dc217629ce53dace0a656da8bb92c0f5d4ce26f04a55ff1ed5e6341541d8c8a963427d52d8fd81cb65f0605

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
